### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by staticgroup** [OpenSurv/OpenSurv#12]
https://github.com/OpenSurv/OpenSurv/blob/4a8f282b2aa747dd5c5999a754336a29884563c6/README.md?plain=1#L117

/etc/opensurvc/logging.yml

should be

/etc/opensurv/logging.yml

shouldnt be a issue can we contribue to doco?

**Comment by SvenVD** [comment]
Off course anyone may contribute, you need to create a pull request for that ( on the v1_latest branch as that is the "bleeding edge"). I fixed this typo in latest, should come to main branch when I promote 1.2beta1 to 1.2. Thanks for reporting!
