### ISSUE TITLE
will not autostart raspberry pi 4b bookworm

### ISSUE THREAD

**Issue by jcrossbdn** [OpenSurv/OpenSurv#19]
pi4b bookworm

ran installer, opensurv will start when you run systemctl start lightdm but will not autostart after a reboot.  

did enable the service (systemctl enable lightdm)

**Comment by SvenVD** [comment]
Only Ubuntu 24.04 LTS is supported atm

**Comment by jcrossbdn** [comment]
There were no errors in the logs and it will start if you run systemctl start lightdm.

Can you add that Ubuntu 24.04 is the only supported OS in the main readme on git, that would have been helpful and prevented this ticket :)

**Comment by SvenVD** [comment]
I made the compatibel Hardware/OS combinations more clear on the discussion board where the readme refers too: https://github.com/OpenSurv/OpenSurv#Hardware-list

**Comment by nonobzh29** [comment]
You're probably running the server version of Raspberry Pi OS.
It will not start any graphical interface by default.
You can check with `systemctl get-default`. You will see `multi-user.target`

You need to change this default to graphical:
`sudo systemctl set-default graphical.target`
Now, after reboot, it will start lightdm and OpenSurv!

**Comment by jcrossbdn** [comment]
That is not the issue in this case.  If I ran systemctl start lightdm everything worked great.  It just would not auto start on boot. Switching to Ubuntu as outlined in the discussion solved that issue, however I ended up going back to rpisurv in the end and it just worked out of the box as I’ve seen for years.JasonSent from my iPhoneOn Dec 21, 2024, at 1:47 PM, nonobzh29 ***@***.***> wrote:﻿
You're probably running the server version of Raspberry Pi OS.
It will not start any graphical interface by default.
You can check with systemctl get-default. You will see multi-user.target
You need to change this default to graphical:
sudo systemctl set-default graphical.target
Now, after reboot, it will start lightdm and OpenSurv!

**Comment by SkyByte** [comment]
> _You need to change this default to graphical:
> sudo systemctl set-default graphical.target_

Worked for me! (Raspberry Pi 3b+ Bookworm)
